### PR TITLE
Sarah 01 growrecipes

### PR DESCRIPTION
**Pull request by sarahbytes**
I added a first take at a lettuce grow recipe config file. Seeking initial feedback on whether this is the right approach.

### CODE REVIEW

**Review by nandantumu — COMMENTED** [review]
This looks pretty good. The first thing is I would make a separate folder under resources called config, and then put the lettuce grow file inside there. The next thing is I would add a section that is maybe called `stage_ordering` or something that has the order of each of the stages previously described. One concern is units, like with temp and DLI. Wondering if `temperature` should just be split out into `air_temperature` and `water_temperature`. Also wondering if the day and night cycle should be specified more, perhaps in saying how many hours are required for each?

**Comment by sarahbytes** [comment]
Good points! I'll work on adding these changes and keep you posted. Yeah, day and night cycle should be specified more. I wonder if I can tie it into the daily light hours.

**Review by nandantumu — COMMENTED** [review]
I wonder if it might be easier to just specify the day night cycles at the top level of this. Just like the stages, defining the day night cycle once, so then we only need to refer to it down the line.

**Review by nandantumu — APPROVED** [review]
I really like this. I think that this should cover the vast majority of grow cases we'll have, and gives us a good amount of flexibility moving forward!

**Pull request merged**
